"""new fields in user model

Revision ID: 80e556ad0a6c
Revises: a8c8edf0147b
Create Date: 2022-10-23 16:54:31.997576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e556ad0a6c'
down_revision = 'a8c8edf0147b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_posts',
    sa.Column('liked_id', sa.Integer(), nullable=True),
    sa.Column('disliked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disliked_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['liked_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_posts')
    # ### end Alembic commands ###
